### ISSUE TITLE
Run tests on a given interview URL from the generating page itself (big job)

### ISSUE THREAD

**Issue by plocket** [plocket/al_story#4]
Is this possible? How would we make this happen? We'd pull dc into here and... what? We'll need it to be on a server locally to develop it properly. Also, would need to display all output.

If not integrating with github to create project, need from user:
- Interview URL of existing project (will break if the interview isn't on the given server, but is the easiest way to go)

If running whole darn thing, need from user all the .env:
- password
- email
- ID?

**Comment by BryceStevenWilley** [comment]
With some advances in Kiln internals, we could theoretically get to a point where we point to a URL and Kiln runs on it. So that's one improvement here.

The rather large downside is that I don't think node will at all be compatible with browser JS, and puppeteer will for certain not run in the browser.

ALKilnInThePlayground I think fills this niche of being able to easy run tests quickly without installing node really well, I think anything we could do here would be better served improving Playground Kiln.

**Comment by plocket** [comment]
I agree, ALKiln Playground fills a very similar role now and could possibly be adapted to do the same job if we integrate it. I made https://github.com/SuffolkLITLab/docassemble-ALKilnInThePlayground/issues/34.
